- name: Deleting Existing Application Directory
  ansible.builtin.file:
    name: "{{ app_path }}"
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    name: "{{ app_path }}"
    state: directory

- name: Download and Extract {{ component }} Code
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_path }}"
    remote_src: true